# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-30 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=500)),
                ('company', models.CharField(max_length=500)),
                ('price', models.IntegerField(default=0)),
                ('launch_date', models.DateField(default=0)),
            ],
        ),
    ]
