# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-30 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='pic',
            field=models.CharField(default=' ', max_length=1000),
        ),
    ]
