# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-07 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_cars_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=1000)),
                ('mobile_no', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UsedCars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=1000)),
                ('price', models.IntegerField(default=0)),
                ('year', models.IntegerField(default=0)),
                ('driven', models.IntegerField(default=0)),
                ('oil', models.CharField(max_length=100)),
                ('owner_type', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='owner',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.UsedCars'),
        ),
    ]
