# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-15 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20160707_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='usedcars',
            name='pic',
            field=models.FileField(default=None, upload_to=b''),
        ),
    ]
